spring:
  application:
    name: api-gateway

  ##GATEWAY CONFIGURATIONS

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        ## user module
        - id: user
          uri: http://localhost:8086
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1




server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka