spring:
  application:
    name: api-gateway

  ##GATEWAY CONFIGURATIONS

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        ## user module
        - id: user
          uri: http://localhost:8091
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        ## module resource
        - id: resource
          uri: http://localhost:8092
          predicates:
            - Path=/resource/**
          filters:
            - StripPrefix=1

        ## module event
        - id: event
          uri: http://localhost:8093
          predicates:
            - Path=/http/**
          filters:
            - StripPrefix=1
        ## module club
        - id: club
          uri: http://localhost:8094
          predicates:
            - Path=/http/**
          filters:
            - StripPrefix=1
server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka